### ISSUE TITLE
Track Descriptions overflow box

### ISSUE THREAD

**Issue by cchu70** [HackGT/hackgteeny2020#3]
<img width="807" alt="Screen Shot 2020-08-23 at 3 14 04 PM" src="https://user-images.githubusercontent.com/34669546/90986793-7bc86b80-e553-11ea-9dc9-b40a5c67b26f.png">

**Comment by Stephanie-A** [comment]
Desktop version, browser, width?

**Comment by cchu70** [comment]
Macbook Pro, mac, Firefox
<img width="309" alt="Screen Shot 2020-08-23 at 3 19 36 PM" src="https://user-images.githubusercontent.com/34669546/90986867-2c366f80-e554-11ea-98b4-b7140b421e72.png">

**Comment by Stephanie-A** [comment]
This should be fixed in the latest release, so I'm closing it now
