### ISSUE TITLE
"Register" font color is black

### ISSUE THREAD

**Issue by cchu70** [HackGT/hackgteeny2020#5]
This is the only text anywhere on the page that is black. I think it should be the same color as the text in the FAQ answers.
<img width="564" alt="Screen Shot 2020-08-23 at 3 22 21 PM" src="https://user-images.githubusercontent.com/34669546/90986918-97804180-e554-11ea-846e-5bc80121d434.png">

**Comment by cchu70** [comment]
This might be abetter question for the designer of the site though

**Comment by Stephanie-A** [comment]
Closing since this is in accordance with the figma and the track descriptions are black.
